global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@polymarket-insider.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: 'YOUR_TELEGRAM_BOT_TOKEN'  # This should be replaced with actual token
        chat_id: YOUR_TELEGRAM_CHAT_ID       # This should be replaced with actual chat ID
        message: '🚨 Alert: {{ .GroupLabels.alertname }} - {{ .Annotations.summary }}'
        parse_mode: 'Markdown'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']