apiVersion: v1
kind: ConfigMap
metadata:
  name: polymarket-insider-config
  namespace: default
data:
  POLYMARKET_API_URL: "https://clob.polymarket.com"
  POLYMARKET_WS_URL: "wss://ws_clob.polymarket.com"
  MIN_TRADE_SIZE_USD: "10000"
  FUNDING_LOOKBACK_HOURS: "24"
  TRADE_HISTORY_CHECK_DAYS: "30"
  LOG_LEVEL: "INFO"