apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polymarket-insider-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard