apiVersion: v1
kind: Secret
metadata:
  name: polymarket-insider-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded values
  # To encode: echo -n "your_token_here" | base64
  TELEGRAM_BOT_TOKEN: eW91cl90ZWxlZ3JhbV9ib3RfdG9rZW5faGVyZQ==  # Replace with actual base64 encoded token
  TELEGRAM_CHAT_ID: eW91cl90ZWxlZ3JhbV9jaGF0X2lkX2hlcmU=  # Replace with actual base64 encoded chat id