apiVersion: v1
kind: Service
metadata:
  name: polymarket-insider-service
  namespace: default
spec:
  selector:
    app: polymarket-insider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP